#!/bin/sh
# Tests for relay-schedule-apply.sh. Runs inside a throwaway container (writes to /etc and
# /usr/local/bin for the systemd-analyze verify step). From the repo root, in Git Bash:
#   MSYS_NO_PATHCONV=1 docker run --rm -v "$(pwd -W)/power/server":/w -w /w debian:trixie \
#     sh -c 'apt-get update -qq && apt-get install -y -qq systemd >/dev/null && sh test/test-apply.sh'
set -u
[ -f /.dockerenv ] || { echo "refusing to run outside a container"; exit 2; }

HERE=$(cd "$(dirname "$0")/.." && pwd)
APPLY=$HERE/relay-schedule-apply.sh
T=$(mktemp -d)
fails=0
pass() { echo "PASS: $*"; }
fail() { echo "FAIL: $*"; fails=$((fails + 1)); }

run_apply() { # dir -> runs apply against $1/plan, $1/units, $1/status
    PLAN=$1/plan STATUS=$1/status UNIT_DIR=$1/units NO_SYSTEMCTL=1 sh "$APPLY"
}

expect_file() { # file expected-content label
    if [ "$(cat "$1" 2>/dev/null)" = "$2" ]; then pass "$3"; else
        fail "$3"; echo "--- got:"; cat "$1" 2>/dev/null; echo "--- want:"; echo "$2"; fi
}

HEADER_A="# Generated by relay-schedule-apply.sh from $T/a/plan. Do not edit.
[Timer]
OnCalendar=
OnCalendar=2000-01-01 00:00:00"

# (a) valid plan
mkdir -p "$T/a"
cat > "$T/a/plan" <<'EOF'
# relay schedule plan, generated 2026-10-12T00:05:00+01:00
warn 2026-10-13 08:55
sleep 2026-10-13 09:00
wake 2026-10-13 12:00

# second gap
warn 2026-10-13 12:55
sleep 2026-10-13 13:00
wake 2026-10-13 17:00
EOF
if out=$(run_apply "$T/a"); then pass "(a) exit 0: $out"; else fail "(a) exit nonzero: $out"; fi
expect_file "$T/a/units/relay-sleep-warn.timer.d/plan.conf" "$HEADER_A
OnCalendar=2026-10-13 08:55:00
OnCalendar=2026-10-13 12:55:00" "(a) warn drop-in"
expect_file "$T/a/units/relay-sleep.timer.d/plan.conf" "$HEADER_A
OnCalendar=2026-10-13 09:00:00
OnCalendar=2026-10-13 13:00:00" "(a) sleep drop-in"
expect_file "$T/a/units/relay-wake.timer.d/plan.conf" "$HEADER_A
OnCalendar=2026-10-13 12:00:00
OnCalendar=2026-10-13 17:00:00" "(a) wake drop-in"
want_hash=$(sha256sum "$T/a/plan" | cut -d' ' -f1)
[ "$(sed -n 1p "$T/a/status")" = "$want_hash" ] && pass "(a) status hash" || fail "(a) status hash"
sed -n 2p "$T/a/status" | grep -Eq '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9:]{8}[+-][0-9]{2}:[0-9]{2}$' \
    && pass "(a) status time" || fail "(a) status time: $(sed -n 2p "$T/a/status")"
[ -z "$(find "$T/a" -name '.*' -type f)" ] && pass "(a) no temp files left" || fail "(a) temp files left"

# (b) every OnCalendar value parses
bad_cal=$(cat "$T"/a/units/*.d/plan.conf | sed -n 's/^OnCalendar=\(..*\)$/\1/p' |
    while IFS= read -r v; do systemd-analyze calendar "$v" >/dev/null 2>&1 || echo "$v"; done)
[ -z "$bad_cal" ] && pass "(b) systemd-analyze calendar accepts all values" \
    || fail "(b) calendar rejects: $bad_cal"

# (c) malformed lines: exit 1, nothing changed
for badline in 'sleep 2026-10-13 9:00' 'sleep 2026-10-13 09:00; rm -rf /' 'nap 2026-10-13 09:00' \
               'sleep 2026-13-45 09:00' 'sleep 2026-10-13 09:00 ' ' sleep 2026-10-13 09:00'; do
    snap=$(cat "$T"/a/units/*.d/plan.conf "$T/a/status")
    cp "$T/a/plan" "$T/a/plan.good"
    printf '%s\n' "$badline" >> "$T/a/plan"
    out=$(run_apply "$T/a"); rc=$?
    [ $rc = 1 ] && pass "(c) '$badline' -> exit 1 ($out)" || fail "(c) '$badline' -> exit $rc"
    [ "$(cat "$T"/a/units/*.d/plan.conf "$T/a/status")" = "$snap" ] \
        && pass "(c) '$badline' -> nothing changed" || fail "(c) '$badline' -> files changed"
    mv "$T/a/plan.good" "$T/a/plan"
done
# CRLF line endings are malformed too
sed 's/$/\r/' "$T/a/plan" > "$T/a/plan.crlf"
PLAN=$T/a/plan.crlf STATUS=$T/a/status UNIT_DIR=$T/a/units NO_SYSTEMCTL=1 sh "$APPLY" >/dev/null
[ $? = 1 ] && pass "(c) CRLF plan rejected" || fail "(c) CRLF plan accepted"
# symlinked plan is refused
ln -s /etc/passwd "$T/a/plan.link"
PLAN=$T/a/plan.link STATUS=$T/a/status UNIT_DIR=$T/a/units NO_SYSTEMCTL=1 sh "$APPLY" >/dev/null
[ $? = 1 ] && pass "(c) symlinked plan refused" || fail "(c) symlinked plan accepted"

# (d) missing plan -> placeholder only, hash of empty input
mkdir -p "$T/d"
if out=$(run_apply "$T/d"); then pass "(d) exit 0: $out"; else fail "(d) exit nonzero: $out"; fi
HEADER_D="# Generated by relay-schedule-apply.sh from $T/d/plan. Do not edit.
[Timer]
OnCalendar=
OnCalendar=2000-01-01 00:00:00"
for u in relay-sleep-warn relay-sleep relay-wake; do
    expect_file "$T/d/units/$u.timer.d/plan.conf" "$HEADER_D" "(d) $u placeholder only"
done
[ "$(sed -n 1p "$T/d/status")" = "$(printf '' | sha256sum | cut -d' ' -f1)" ] \
    && pass "(d) status = sha256 of empty" || fail "(d) status hash"

# (e) systemd-analyze verify the installed units + generated drop-ins
for s in relay-sleep.sh relay-wifi-fix.sh relay-schedule-apply.sh; do
    install -m 755 "$HERE/$s" /usr/local/bin/$s
done
install -m 644 "$HERE"/*.timer "$HERE"/*.service "$HERE"/*.path /etc/systemd/system/
cp "$T/a/plan" "$T/plan-e"
PLAN=$T/plan-e STATUS=$T/status-e UNIT_DIR=/etc/systemd/system NO_SYSTEMCTL=1 sh "$APPLY" >/dev/null \
    || fail "(e) apply into /etc/systemd/system"
vout=$(cd /etc/systemd/system && systemd-analyze verify relay-*.timer relay-*.service relay-*.path 2>&1)
vrc=$?
# Container noise unrelated to our units (no running systemd, missing deps of the host).
vreal=$(echo "$vout" | grep -v -e 'Failed to prepare filename' -e 'No such file or directory' \
    -e 'is not executable' -e '^$' || true)
if [ $vrc = 0 ] && [ -z "$vreal" ]; then pass "(e) systemd-analyze verify clean"; else
    fail "(e) systemd-analyze verify rc=$vrc"; echo "$vout"; fi
echo "--- relay-sleep.timer effective OnCalendar (systemd-analyze cat-config):"
systemd-analyze cat-config systemd/system/relay-sleep.timer 2>/dev/null | grep -E '^(# /|OnCalendar)' || true

rm -rf "$T"
echo "=== $fails failure(s)"
[ $fails = 0 ]
