#!/bin/sh
# Apply the runner's schedule plan (shared/API.md "Schedule plan file") to the
# relay-sleep-warn/relay-sleep/relay-wake timers as OnCalendar= drop-ins.
# Runs as root via relay-schedule-apply.service (triggered by relay-schedule.path).
# Any invalid line rejects the whole plan and changes nothing.
# Env overrides (tests): PLAN, STATUS, UNIT_DIR, NO_SYSTEMCTL=1.
set -eu

PLAN=${PLAN:-/var/lib/relay/schedule-plan}
STATUS=${STATUS:-/var/lib/relay/schedule-applied}
UNIT_DIR=${UNIT_DIR:-/etc/systemd/system}
PATTERN='^(warn|sleep|wake) [0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}$'
# A timer with zero triggers refuses to start; a past date never fires (Persistent=false).
PLACEHOLDER='2000-01-01 00:00:00'

log() { echo "relay-schedule-apply: $*"; }

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT
copy=$tmpdir/plan

# Snapshot the plan once so validation, drop-ins and the hash all see the same bytes.
# The plan lives in a directory the unprivileged runner owns: never follow a symlink.
if [ -L "$PLAN" ]; then
    log "refusing: $PLAN is a symlink"; exit 1
elif [ -e "$PLAN" ]; then
    [ -f "$PLAN" ] || { log "refusing: $PLAN is not a regular file"; exit 1; }
    cat "$PLAN" > "$copy"
else
    : > "$copy"
fi

# Validate: every non-empty, non-comment line must match PATTERN and be a real date/time.
bad=$(grep -nEv '^(#.*)?$' "$copy" | grep -Ev "^[0-9]+:${PATTERN#^}" | head -n 1 || true)
if [ -n "$bad" ]; then
    log "plan rejected, bad line $(printf '%s' "$bad" | cut -c1-120)"; exit 1
fi
grep -E "$PATTERN" "$copy" > "$tmpdir/events" || true
while read -r kind day hm; do
    if ! TZ=UTC date -d "$day $hm" >/dev/null 2>&1; then
        log "plan rejected, invalid date/time: $kind $day $hm"; exit 1
    fi
done < "$tmpdir/events"

unit_for() {
    case $1 in
        warn)  echo relay-sleep-warn.timer ;;
        sleep) echo relay-sleep.timer ;;
        wake)  echo relay-wake.timer ;;
    esac
}
count() { grep -c "^$1 " "$tmpdir/events" || true; }

# Build every drop-in first, then move each into place atomically.
for kind in warn sleep wake; do
    {
        echo "# Generated by relay-schedule-apply.sh from $PLAN. Do not edit."
        echo "[Timer]"
        echo "OnCalendar="
        echo "OnCalendar=$PLACEHOLDER"
        grep "^$kind " "$tmpdir/events" | while read -r _ day hm; do
            echo "OnCalendar=$day $hm:00"
        done
    } > "$tmpdir/$kind.conf"
done
for kind in warn sleep wake; do
    dir=$UNIT_DIR/$(unit_for "$kind").d
    mkdir -p "$dir"
    tmp=$(mktemp "$dir/.plan.conf.XXXXXX")
    cat "$tmpdir/$kind.conf" > "$tmp"
    chmod 644 "$tmp"
    mv -f "$tmp" "$dir/plan.conf"
done

if [ "${NO_SYSTEMCTL:-0}" != 1 ]; then
    systemctl daemon-reload
    systemctl restart relay-sleep-warn.timer relay-sleep.timer relay-wake.timer
fi

hash=$(sha256sum < "$copy" | cut -d' ' -f1)
stmp=$(mktemp "$(dirname "$STATUS")/.schedule-applied.XXXXXX")
printf '%s\n%s\n' "$hash" "$(date -Iseconds)" > "$stmp"
chmod 644 "$stmp"
mv -f "$stmp" "$STATUS"

log "applied plan $hash: warn=$(count warn) sleep=$(count sleep) wake=$(count wake)"
